### PR TITLE
adding App.css styling for many elements. Also, adding images folder …

### LINKED ISSUE #5: CSS colours of brand , logo , images
### Description:
The business uses specific colours, which we need to follow for branding reasons. It follows the rule of 60 30 10 in percentages + specific black and white. Those are:

- RED
HEX: #fe3253
RGB: (254, 50, 83)

- GREY
HEX: #4D4D4D
RGB: (77, 77, 77)

- BLUE
HEX: #004E74 
RGB: (0, 78, 116)

- *WHITE
HEX: #efe6e6 
RGB: (239, 230, 230, 1)

- **BLACK
HEX: #0f0202 
RGB: (15, 2, 2, 1)

### Priority:
[Medium]

### Type:
[Branding]

### User story - Current Behaviour:
User must see more than 90% the colours above

### User Story - Expected Behaviour:
Users sees on more than 90% the colours mentioned above.

### Steps to Reproduce:
N/A

### Screenshots:
Attached below the logo of the brand and other icons to be used later on.

### Branch Name:
css-logo-and-images

### Additional Information:
Those colours must be followed throughout the project and wherever there is choice for colouring. 

### Acceptance Criteria:
The colours you see are from the above mentioned.
Creation of Images folder with the below logo and icons

### Subtasks:
N/A

### Assignees:
- **Leading Developer:** @nikomakr 
- **Leading QA:** @clamadi

### Labels:
[Branding, logo, icons]

### Due Date:
[18/01/2024]

### Dependencies:
None

### Notes for Reviewers:
Please, use those colours and logo for anything needed.

### PR DESCRIPTION
**Pull request by nikomakr**
@clamadi can you please this one?
It's very straight forward check going from nothing on App.css to have almost everything.
Also, from nothing to having images folder with logo and icons.
Thank you

### CODE REVIEW

**Review by clamadi — CHANGES_REQUESTED** [review]
Hi @nikomakr, the logo and images added looks good.

However, I think styling should be done when the major components on the page has been added. so that there are no discrepancies especially with elements created on the components and we don't duplicate codes as well. That way we get to appreciate the styling better so i would suggest this CSS styling should be left until the end the major MVP are added. Either split this branch into two one for image folder which can go now and the second for CSS styling which should wait until the end of MVP implementation.

thanks

**Comment by nikomakr** [comment]
Hi @clamadi ,

I see that as not merged to the main branch.
The reason I chose to work on it yesterday was to avoid clashing with anything else rest of team was working on. 
I see nothing no dependencies and nothing else holding you back.
Can you please merge it to the main branch?

We can revisit it if we want any changes the upcoming days.

Thanks,
N

**Review by d-sholaakanbi — APPROVED** [review]
Nice css styling!!

**Comment by nikomakr** [comment]
@clamadi can you please re-visit this one? Can you please merge it to the main branch? Thanks

**Review by clamadi — APPROVED** [review]

**Pull request merged**
